### ISSUE TITLE
Unnecessary step

### ISSUE THREAD

**Issue by LiamDawe** [mikeroyal/Steam-Deck-Guide#2]
Hi, the section on installing Flatpak is simply not needed, it's setup out of the box.

**Comment by LiamDawe** [comment]
Same with enabling Proton, it's also setup out of the box.

**Comment by mikeroyal** [comment]
Hi @LiamDawe, sorry for the late response been a crazy work week for me. Anyways, the steps you mention above are unnecessary now I agree. I was going to remove them but I've had folks new to linux reach out to me from finding the steam deck guide. They said those steps for them were helpful in their Linux Gaming journey on their own Linux PCs. So I do plan on removing those steps in future but will keep them for now as new users to Linux outside the Steam Deck ecosystem have found them useful. So thank you for the suggest and keep up the great Linux Gaming content you create!
