### ISSUE TITLE
Adding Parsec to the Streaming Clients

### ISSUE THREAD

**Issue by NightHammer1000** [mikeroyal/Steam-Deck-Guide#7]
Parsec should not be missing from the Game Streaming Clients.

Still one of the best and Hassle free Providers I tried for In-Home and especially for Remote

https://parsec.app/

**Comment by mikeroyal** [comment]
It's been added now.

**Comment by NightHammer1000** [comment]
Something to add to this is that Parsec currently has a Bug that only allows Software Decoding in Gaming Mode.
The Devs are Aware of it. The Problem has been identified, and a fix has already been tested by me together with a Dev.
Only a matter of Time until it lands in the Official Version.
