### ISSUE TITLE
I have a Brazilian Portuguese version

### ISSUE THREAD

**Issue by valdecircarvalho** [mikeroyal/Steam-Deck-Guide#93]
Hello! 
I have used your guide as one of my inspirations to create a Brazilian Portuguese version of the Steam Deck Guide and it's published here http://steamdeck.valdecir.me/ 
If you want to add to your list - perhaps a session with other languages - will be really nice.
Cheers and keep up the good work and thank you for you effort to the Steam Deck community

**Comment by mikeroyal** [comment]
Wow, thank you for doing that. I would like to add more translations of the guide for Steam Deck users around the world.

**Comment by mikeroyal** [comment]
Made A PR to have this added. Thank you for this contribution!
