### ISSUE TITLE
Add Btrfs-SteamOS

### ISSUE THREAD

**Issue by RecentRunner** [mikeroyal/Steam-Deck-Guide#99]
I've been using it on my steam deck for a few months and I haven't had any problems so far, feel like it should be mentioned at the very least

https://gitlab.com/popsulfr/steamos-btrfs

**Comment by mikeroyal** [comment]
It has been in the guide for months now. https://github.com/mikeroyal/Steam-Deck-Guide/blob/main/Games%20and%20Software/Operating%20Systems.md
